### ISSUE TITLE
Maybe switch to Postgre

### ISSUE THREAD

**Issue by n-peugnet** [club-1/webdav-server#1]
Currently, calendar, locks and address-books are stored on sqlite databases on a per user basis. This allows each user to easily make a copy of its data, but at the same time it is very easy to delete by mistake. Also The backup will not use a dump of the database so it could be corrupted.

This is why merging all the user data in a single Postgre database could be a better solution.

Having only one database would also make it possible to share calendars between users of club1.fr.

WDYT @vincent-peugnet  ?

**Comment by vincent-peugnet** [comment]
Mmh, yeah, I think I'm 100% for the postegre database solution

**Comment by n-peugnet** [comment]
Great, I was not 100% sure. I'll make the change soon. But all previous addressbooks and calendars will be erased.

**Comment by vincent-peugnet** [comment]
It's fine for me as I haven't created any of thoses
